http://localhost:3000/

GET api/sessions

Content-Type: application/json

POST api/sessions
{
  "email": "test@test.com",
  "password": "123"
}

http://localhost:3002

Content-Type: application/json

POST /login
{
  "email": "testtest.com",
  "password": "12345678"
}
