export const Texts = {
  email: 'Email',
  password: 'Password',
  wrongCredentials: 'Wrong credentials entered',
  keepMeLoggedIn: 'Keep me logged in',
  login: 'Login',
  doNotHaveAccount: "Don't have an account?",
  signUp: 'Sign up',
  signIn: 'Sign in',
  pleaseLogIn: 'Please log in with the data you entered during registration.',
  emailRuleFail: 'Please provide correct email',
  passwordRuleFail: 'Please provide correct password',
  homeWelcome: 'Welcome',
  successFullLogin: 'Successfully logged in',
  profile: 'Profile',
  logout: 'Logout',
  successFullLogout: 'Successfully logged out',
}
